# Generated by Django 5.1 on 2024-10-05 17:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_by",
            field=models.CharField(
                choices=[("U", "User"), ("C", "Chatbot")], default="U", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("S", "Sent"), ("R", "Read")], default="S", max_length=1
            ),
        ),
    ]
